apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: param-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: argocdapp-param-demo  
    server: 'https://kubernetes.default.svc'
  source:
    path: 0-Demo_Files/Params_Demo
    repoURL: 'https://github.com/SMACAcademy/ArgoCD-Complete-Master-Course.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
