apiVersion: v1
kind: ResourceQuota
metadata:
  name: argodemo-ns-quota
  namespace: argodemo
spec:
  hard:
    pods: "4"
    services: "5"
    replicationcontrollers: "5"
    secrets: "10"
    configmaps: "10"
    persistentvolumeclaims: "4"
    requests.cpu: "1000m"
    requests.memory: "1Gi"
    limits.cpu: "2000m"
    limits.memory: "2Gi"
