apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-app2
  labels:
    app: nginx-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app2
  template:
    metadata:
      labels:
        app: nginx-app2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
